markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: page/:num

blog:
    name: 梅爽                                               # 博客名称
    description: 个人博客                                         # 博客描述
    title: 听见下雨的声音                                              # 网页标题
    url: Shuang-Mei.github.io                                        # 博客地址
    qiniu:                                               # 七牛云地址
author:
    name: 梅爽                                               # 作者名称
    email: 850762409@qq.com                                              # 邮箱地址
    weibo: http://www.weibo.com/u/2890605417/home?wvr=5                                              # 微博地址
    github: https://github.com/Shuang-Mei                                             # GitHub地址
    logo: http://chuantu.biz/t2/23/1451965983x-1376436656.jpg # logo地址
    url: Shuang-Mei.github.io                                        # 博客地址
    douban: 
        name:                                            # 豆瓣地址名称
        key:               # 豆瓣API Key

